#pragma once

#define ImFluentIcon_Back            "\xEE\x83\x8A"
#define ImFluentIcon_BackArrow       "\xEE\x9C\xAB"
#define ImFluentIcon_Forward         "\xEE\x9C\xAC"
#define ImFluentIcon_GlobalNavButton "\xEE\x9C\x80"
#define ImFluentIcon_Home            "\xEE\xA0\x8F"
#define ImFluentIcon_Search          "\xEE\x9C\x9F"
#define ImFluentIcon_Settings        "\xEE\x9C\x93"
#define ImFluentIcon_More            "\xEE\x9C\x92"
#define ImFluentIcon_Refresh         "\xEE\x9C\x92"
#define ImFluentIcon_Pin             "\xEE\xA0\x88"

#define ImFluentIcon_Add             "\xEE\x9C\x90"
#define ImFluentIcon_Remove          "\xEE\x9C\x91"
#define ImFluentIcon_Cancel          "\xEE\x9C\x91"
#define ImFluentIcon_Check           "\xEE\x9C\xBE"
#define ImFluentIcon_Save            "\xEE\x9D\x85"
#define ImFluentIcon_Delete          "\xEE\x9D\x84"
#define ImFluentIcon_Edit            "\xEE\x9C\x90"
#define ImFluentIcon_Copy            "\xEE\x9C\x8C"
#define ImFluentIcon_Paste           "\xEE\xA3\x9D"
#define ImFluentIcon_Cut             "\xEE\xA3\x9E"

#define ImFluentIcon_ChevronUp       "\xEE\x9D\x90"
#define ImFluentIcon_ChevronDown     "\xEE\x9C\x8D"
#define ImFluentIcon_ChevronLeft     "\xEE\x9D\x96"
#define ImFluentIcon_ChevronRight    "\xEE\x9D\x95"

#define ImFluentIcon_Info            "\xEE\xA5\x86"
#define ImFluentIcon_InfoSolid       "\xEF\x96\xA1"
#define ImFluentIcon_Warning         "\xEE\x9D\xA3"
#define ImFluentIcon_ErrorBadge      "\xEE\xA3\x83"
#define ImFluentIcon_CheckmarkCircle "\xEE\xA1\x9F"
#define ImFluentIcon_Important       "\xEE\xAB\x90"

#define ImFluentIcon_RadioBtn        "\xEE\xA4\x95"
#define ImFluentIcon_RadioBtnOn      "\xEE\xA4\x94"
#define ImFluentIcon_CheckboxOff     "\xEE\x9D\xA9"
#define ImFluentIcon_CheckboxOn      "\xEE\x9D\xA8"
#define ImFluentIcon_CheckboxIndet   "\xEE\xA1\xB7"

#define ImFluentIcon_Folder          "\xEE\xA3\x88"
#define ImFluentIcon_OpenFile        "\xEE\xA3\xA3"
#define ImFluentIcon_NewFolder       "\xEE\xA4\xBE"
#define ImFluentIcon_Document        "\xEE\xA1\x80"

#define ImFluentIcon_Play            "\xEE\x9D\x88"
#define ImFluentIcon_Pause           "\xEE\x9D\x89"
#define ImFluentIcon_Stop            "\xEE\x9D\x8B"
#define ImFluentIcon_Volume          "\xEE\x9D\x9F"

#define ImFluentIcon_Mail            "\xEE\x9C\x95"
#define ImFluentIcon_People          "\xEE\x9C\x96"
#define ImFluentIcon_Contact         "\xEE\x9D\x9D"
#define ImFluentIcon_Phone           "\xEE\x9C\x97"

#define ImFluentIcon_View            "\xEE\xA2\x90"
#define ImFluentIcon_Hide            "\xEE\xA2\x91"

#define ImFluentIcon_Calendar        "\xEE\x9D\x87"
#define ImFluentIcon_Clock           "\xEE\x9D\x86"

#define ImFluentIcon_Fundamentals    "\xEE\xA3\xB1"
#define ImFluentIcon_Design          "\xEE\xAC\xBC"
#define ImFluentIcon_Color           "\xEE\x9E\x90"
#define ImFluentIcon_Geometry        "\xEE\x9D\x83"
#define ImFluentIcon_Iconography     "\xEE\xB5\x98"
#define ImFluentIcon_Spacing         "\xEE\xA2\xB3"
#define ImFluentIcon_Typography      "\xEE\xA3\x92"
#define ImFluentIcon_Accessibility   "\xEE\x9D\xB6"
#define ImFluentIcon_AllControls     "\xEE\xA2\xA9"

#define ImFluentIcon_Star            "\xEE\x9D\xB4"
#define ImFluentIcon_StarFilled      "\xEE\x9D\xB5"
#define ImFluentIcon_Heart           "\xEE\x9D\xB7"
#define ImFluentIcon_Like            "\xEE\xA4\x8B"
#define ImFluentIcon_Download        "\xEE\xA2\x96"
#define ImFluentIcon_Upload          "\xEE\xA2\x98"
#define ImFluentIcon_Share           "\xEE\x9D\xA2"
#define ImFluentIcon_Print           "\xEE\xA2\x89"
